### ISSUE TITLE
"correctness" of example?

### ISSUE THREAD

**Issue by nabati** [stevenpetryk/jsonapi-normalizer#12]
Out of curiosity

![image](https://user-images.githubusercontent.com/1499050/37470945-f78bea12-2868-11e8-8a3d-c715f56993d8.png)

Does it really make sense that there is no way to know what the primary data is from the response in the normalized output?

```
  result: {
    articles: ['1'],
    users: ['42']
  },
```

**Comment by stevenpetryk** [comment]
This is a great point. I think it is a flawed implementation—`result` should only contain the primary object.

**Comment by stevenpetryk** [comment]
This has been fixed in `2.0.1`.
