### ISSUE TITLE
Meta data

### ISSUE THREAD

**Issue by tommyalvarez** [stevenpetryk/jsonapi-normalizer#13]
Hi,

I was wondering if it's a bug that when sending the json-api response with meta data, gets filtered out. For e.g. 
```
...
meta: {
pages: 5
current_page: 4
}
....
```
When applying normalizer, this data is discarded

**Comment by stevenpetryk** [comment]
That is not a bug. This information should not be part of your `entities`, it should be kept elsewhere in state (like in a paginator). If you show me some specifics, I could help point you in the right direction!
