### ISSUE TITLE
The implementation

### ISSUE THREAD

**Issue by yury-dymov** [stevenpetryk/jsonapi-normalizer#8]
Hi Steven,

I've reviewed an issue in a normalizr repo and found the mention of your library.
I've released very similar thing called [json-api-normalizer](https://github.com/yury-dymov/json-api-normalizer) with slightly different implementation ideas. Maybe you can have a look, and we can discuss if we can somehow merge our efforts.

Kind regards,
Yury.

**Comment by stevenpetryk** [comment]
Hey there! It seems like your project has a much broader scope than this one. I wish I had known about it before rolling my own. I would like to keep this repo separate simply because it is largely unmaintained (this got popular on accident, it was just meant to support a school project 😊).
